### ISSUE TITLE
can support registry for polarismesh

### ISSUE THREAD

**Issue by chuntaojun** [zeromicro/zero-contrib#1]
I hope go-zero can support registry for polarismesh, if accept, I will do it

**Comment by kevwan** [comment]
Thanks!

Would you please describe a little bit on how to support it?

**Comment by chuntaojun** [comment]
I will follow the design of the registry interface in go-zero, and connect through the polaris-go of the polarismesh community, so that the go-zero service registration can use polarismesh.

**Comment by kevwan** [comment]
Appreciate to add the implementation in zero-contrib, please put it the place like the implementations of consul and nacos.

Thanks in advance!

**Comment by chuntaojun** [comment]
> Appreciate to add the implementation in zero-contrib, please put it the place like the implementations of consul and nacos.
> 
> Thanks in advance!

I have already submitted the relevant pr, but it is troublesome @ kevwan has time to help review

**Comment by kevwan** [comment]
Thanks for your PR, I'll do that later.

**Comment by chuntaojun** [comment]
I submitted the pr corresponding to the quick experience of polaris in the examples project, and I have worked hard to take a look

https://github.com/zeromicro/zero-examples/pull/11
