### ISSUE TITLE
Consul ttl expired

### ISSUE THREAD

**Issue by neccohuang** [zeromicro/zero-contrib#12]
Will it cause consul ttl expired ?
The update time should be less than the ttl setting to avoid expiration.

![alt ttl](https://i.imgur.com/enNsRrW.jpeg)

**Comment by dfang** [comment]
是的 下面一个值应该小于上面的值， 否则服务状态会不间断的抽风

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/1277047/159650158-1cb5b8af-fb94-47aa-874e-efea85e1f4f1.png">
