### ISSUE TITLE
希望增加NotLoadCacheAtStart可选参数

### ISSUE THREAD

**Issue by lichengguo** [zeromicro/zero-contrib#169]
希望增加NotLoadCacheAtStart可选参数，不然本地调试每次都要删除cache。
![图片](https://github.com/zeromicro/zero-contrib/assets/31106742/f071aa15-4b38-4040-81f8-7dfb5d6dbdcf)

**Comment by linfun486** [comment]
或者解决下nacos cache将serviceName 缓存为group+serviceName的情况
<img width="357" alt="图片" src="https://github.com/zeromicro/zero-contrib/assets/5285142/534b692b-bed9-4924-b314-0b88b2601dbc">
