### ISSUE TITLE
consul 服务发现使用方法

### ISSUE THREAD

**Issue by giantwu** [zeromicro/zero-contrib#285]
您好，使用consul为服务注册组件，服务发现时 需要怎么配置呢？用了example下的consul测试代码，是不通的。

**Comment by MaxToby** [comment]
[https://github.com/zeromicro/zero-examples/tree/main/discovery/consul](https://github.com/zeromicro/zero-examples/tree/main/discovery/consul) 我这边测试是正常的。

**Comment by giantwu** [comment]
收到，我的版本低，升级以后都好使了，多谢。
